<?php

use Illuminate\Database\Seeder;

class MissionsTableSeeder extends Seeder
{

	public function run()
	{
		$missions = [
			['id' => 1, 'name' => 'Agregar foto', 'description' => 'Subir una foto al perfil del usuario', 'awarded_points' => 5, 
			'redeemable_points' => 0, 'goal' => 1, 'variable_id' => 7, 'league_id' => null, 'badge_id' => 1, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 2, 'name' => 'Completar perfil', 'description' => 'Completar el 100% del perfil del jugador', 'awarded_points' => 10, 
			'redeemable_points' => 0, 'goal' => 1, 'variable_id' => 7, 'league_id' => null, 'badge_id' => 2, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 3, 'name' => 'Núcleo familiar', 'description' => 'Agregar los datos de un miembro de la familia en la plataforma', 
			'awarded_points' => 10, 'redeemable_points' => 0, 'goal' => 1, 'variable_id' => 7, 'league_id' => null, 'badge_id' => 3, 
			'parent_id' => null, 'type_id' => 2, 'team_id' => null],
			['id' => 4, 'name' => 'Primer logro', 'description' => 'Publicar el primer logro en la plataforma', 'awarded_points' => 5, 
			'redeemable_points' => 0, 'goal' => 1, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 4, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 5, 'name' => 'Cinco logros', 'description' => 'Publicar cinco logros diferentes en la plataforma', 'awarded_points' => 8, 
			'redeemable_points' => 0, 'goal' => 5, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 5, 'parent_id' => 4, 
			'type_id' => 2, 'team_id' => null],
			['id' => 6, 'name' => 'Diez logros', 'description' => 'Publicar diez logros diferentes en la plataforma', 'awarded_points' => 10, 
			'redeemable_points' => 0, 'goal' => 10, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 6, 'parent_id' => 5, 
			'type_id' => 2, 'team_id' => null],
			['id' => 7, 'name' => 'Veinte logros', 'description' => 'Publicar veinte logros diferentes en la plataforma', 'awarded_points' => 20, 
			'redeemable_points' => 0, 'goal' => 20, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 7, 'parent_id' => 6, 
			'type_id' => 2, 'team_id' => null],
			['id' => 8, 'name' => 'Publicar logro', 'description' => 'Publicar un nuevo logro en la plataforma', 'awarded_points' => 1, 
			'redeemable_points' => 0, 'goal' => 1, 'variable_id' => 6, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 9, 'name' => 'Primer curso', 'description' => 'Completar el primer curso en la plataforma', 'awarded_points' => 10, 
			'redeemable_points' => 10, 'goal' => 1, 'variable_id' => 1, 'league_id' => 1, 'badge_id' => 8, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 10, 'name' => 'Cinco cursos', 'description' => 'Completar cinco cursos en la plataforma', 'awarded_points' => 25, 
			'redeemable_points' => 25, 'goal' => 5, 'variable_id' => 1, 'league_id' => null, 'badge_id' => 9, 'parent_id' => 9, 
			'type_id' => 2, 'team_id' => null],
			['id' => 11, 'name' => 'Diez cursos', 'description' => 'Completar diez cursos en la plataforma', 'awarded_points' => 50, 
			'redeemable_points' => 50, 'goal' => 10, 'variable_id' => 1, 'league_id' => null, 'badge_id' => 10, 'parent_id' => 10, 
			'type_id' => 2, 'team_id' => null],
			['id' => 12, 'name' => 'Veinte cursos', 'description' => 'Completar veinte cursos en la plataforma', 'awarded_points' => 100, 
			'redeemable_points' => 100, 'goal' => 20, 'variable_id' => 1, 'league_id' => null, 'badge_id' => 11, 'parent_id' => 11, 
			'type_id' => 2, 'team_id' => null],
			['id' => 13, 'name' => 'Mejor alumno', 'description' => 'Ser el mejor jugador en un curso', 'awarded_points' => 10, 
			'redeemable_points' => 10, 'goal' => 1, 'variable_id' => 8, 'league_id' => null, 'badge_id' => 12, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 14, 'name' => 'Mejor alumno cinco cursos', 'description' => 'Ser el mejor jugador en cinco cursos diferentes', 'awarded_points' => 25, 
			'redeemable_points' => 25, 'goal' => 5, 'variable_id' => 8, 'league_id' => null, 'badge_id' => 13, 'parent_id' => 13, 
			'type_id' => 2, 'team_id' => null],
			['id' => 15, 'name' => 'Mejor alumno diez cursos', 'description' => 'Ser el mejor jugador en diez cursos diferentes', 'awarded_points' => 50, 
			'redeemable_points' => 50, 'goal' => 10, 'variable_id' => 8, 'league_id' => null, 'badge_id' => 14, 'parent_id' => 14, 
			'type_id' => 2, 'team_id' => null],
			['id' => 16, 'name' => 'Mejor alumno veinte cursos', 'description' => 'Ser el mejor jugador en veinte cursos diferentes', 'awarded_points' => 100, 
			'redeemable_points' => 100, 'goal' => 20, 'variable_id' => 8, 'league_id' => null, 'badge_id' => 15, 'parent_id' => 15, 
			'type_id' => 2, 'team_id' => null],
			['id' => 17, 'name' => 'Dar primer comentario', 'description' => 'Comentar por primera vez en una publicación de otro jugador', 'awarded_points' => 5, 
			'redeemable_points' => 5, 'goal' => 1, 'variable_id' => 9, 'league_id' => null, 'badge_id' => 16, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 18, 'name' => 'Dar veinte comentarios', 'description' => 'Realizar veinte comentarios positivos a las publicaciones de otros jugadores', 
			'awarded_points' => 20, 'redeemable_points' => 10, 'goal' => 20, 'variable_id' => 9, 'league_id' => null, 'badge_id' => null, 'parent_id' => 17, 
			'type_id' => 2, 'team_id' => null],
			['id' => 19, 'name' => 'Dar cincuenta comentarios', 'description' => 'Realizar cincuenta comentarios positivos a las publicaciones de otros jugadores', 
			'awarded_points' => 50, 'redeemable_points' => 25, 'goal' => 50, 'variable_id' => 9, 'league_id' => null, 'badge_id' => null, 'parent_id' => 18, 
			'type_id' => 2, 'team_id' => null],
			['id' => 20, 'name' => 'Dar cien comentarios', 'description' => 'Realizar cien comentarios positivos a las publicaciones de otros jugadores', 
			'awarded_points' => 100, 'redeemable_points' => 50, 'goal' => 100, 'variable_id' => 9, 'league_id' => null, 'badge_id' => null, 'parent_id' => 19, 
			'type_id' => 2, 'team_id' => null],
			['id' => 21, 'name' => 'Dar comentario positivo', 'description' => 'Realizar comentarios positivos a las publicaciones de otros jugadores', 
			'awarded_points' => 1, 'redeemable_points' => 0, 'goal' => 1, 'variable_id' => 9, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 22, 'name' => 'Dar primer me gusta', 'description' => 'Dar me gusta por primera vez en una publicación de otro jugador', 'awarded_points' => 2, 
			'redeemable_points' => 0, 'goal' => 1, 'variable_id' => 5, 'league_id' => null, 'badge_id' => 18, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 23, 'name' => 'Dar veinte me gusta', 'description' => 'Dar veinte me gusta a las publicaciones de otros jugadores', 
			'awarded_points' => 10, 'redeemable_points' => 0, 'goal' => 20, 'variable_id' => 5, 'league_id' => null, 'badge_id' => null, 'parent_id' => 22, 
			'type_id' => 2, 'team_id' => null],
			['id' => 24, 'name' => 'Dar cincuenta me gusta', 'description' => 'Dar cincuenta me gustas a las publicaciones de otros jugadores', 
			'awarded_points' => 20, 'redeemable_points' => 0, 'goal' => 50, 'variable_id' => 5, 'league_id' => null, 'badge_id' => null, 'parent_id' => 23, 
			'type_id' => 2, 'team_id' => null],
			['id' => 25, 'name' => 'Dar cien me gusta', 'description' => 'Dar cien me gusta a las publicaciones de otros jugadores', 
			'awarded_points' => 40, 'redeemable_points' => 0, 'goal' => 100, 'variable_id' => 5, 'league_id' => null, 'badge_id' => null, 'parent_id' => 24, 
			'type_id' => 2, 'team_id' => null],
			['id' => 26, 'name' => 'Me gusta', 'description' => 'Dar me gusta a las publicaciones de otros jugadores', 
			'awarded_points' => 1, 'redeemable_points' => 0, 'goal' => 1, 'variable_id' => 5, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 27, 'name' => 'Me gusta', 'description' => 'Dar me gusta a las publicaciones de otros jugadores', 
			'awarded_points' => 1, 'redeemable_points' => 0, 'goal' => 1, 'variable_id' => 5, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 28, 'name' => 'Recibir primer comentario', 'description' => 'Recibir un comentario por primera vez en una publicación', 'awarded_points' => 5, 
			'redeemable_points' => 5, 'goal' => 1, 'variable_id' => 9, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 29, 'name' => 'Recibir cinco comentarios', 'description' => 'Recibir cinco comentarios positivos a una publicación', 
			'awarded_points' => 10, 'redeemable_points' => 10, 'goal' => 5, 'variable_id' => 9, 'league_id' => null, 'badge_id' => null, 'parent_id' => 28, 
			'type_id' => 2, 'team_id' => null],
			['id' => 30, 'name' => 'Recibir diez comentarios', 'description' => 'Recibir diez comentarios positivos a una publicación', 
			'awarded_points' => 20, 'redeemable_points' => 20, 'goal' => 10, 'variable_id' => 9, 'league_id' => null, 'badge_id' => null, 'parent_id' => 29, 
			'type_id' => 2, 'team_id' => null],
			['id' => 31, 'name' => 'Recibir comentario positivo', 'description' => 'Recibir comentarios positivos a una publicación', 
			'awarded_points' => 1, 'redeemable_points' => 0, 'goal' => 1, 'variable_id' => 9, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 32, 'name' => 'Obtener primer ascenso', 'description' => 'Recibir una promoción dentro de la empresa al presentarse a una oportunidad', 
			'awarded_points' => 100, 'redeemable_points' => 100, 'goal' => 1, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 18, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 33, 'name' => 'Primer empleado del mes', 'description' => 'Recibir mención como empleado del mes por primera vez', 
			'awarded_points' => 10, 'redeemable_points' => 10, 'goal' => 1, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 19, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 34, 'name' => 'Quinto empleado del mes', 'description' => 'Recibir mención como empleado del mes cinco veces', 
			'awarded_points' => 25, 'redeemable_points' => 25, 'goal' => 5, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 20, 'parent_id' => 33, 
			'type_id' => 2, 'team_id' => null],
			['id' => 35, 'name' => 'Décimo empleado del mes', 'description' => 'Recibir mención como empleado del mes diez veces', 
			'awarded_points' => 50, 'redeemable_points' => 50, 'goal' => 10, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 21, 'parent_id' => 34, 
			'type_id' => 2, 'team_id' => null],
			['id' => 36, 'name' => 'Empleado del mes', 'description' => 'Recibir mención como empleado del mes', 
			'awarded_points' => 10, 'redeemable_points' => 10, 'goal' => 1, 'variable_id' => 6, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 37, 'name' => 'Primer empleado del año', 'description' => 'Recibir mención como empleado del año por primera vez', 
			'awarded_points' => 100, 'redeemable_points' => 100, 'goal' => 1, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 22, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 38, 'name' => 'Tercer empleado del año', 'description' => 'Recibir mención como empleado del año tres veces', 
			'awarded_points' => 250, 'redeemable_points' => 250, 'goal' => 3, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 23, 'parent_id' => 36, 
			'type_id' => 2, 'team_id' => null],
			['id' => 39, 'name' => 'Quinto empleado del año', 'description' => 'Recibir mención como empleado del año cinco veces', 
			'awarded_points' => 500, 'redeemable_points' => 500, 'goal' => 5, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 24, 'parent_id' => 37, 
			'type_id' => 2, 'team_id' => null],
			['id' => 40, 'name' => 'Empleado del año', 'description' => 'Recibir mención como empleado del año', 
			'awarded_points' => 30, 'redeemable_points' => 30, 'goal' => 1, 'variable_id' => 6, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 41, 'name' => 'Aniversario', 'description' => 'Cumplir el primer año trabajando en la empresa', 
			'awarded_points' => 50, 'redeemable_points' => 50, 'goal' => 1, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 25, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 42, 'name' => 'Quinquenio', 'description' => 'Cumplir cinco años trabajando en la empresa', 
			'awarded_points' => 250, 'redeemable_points' => 250, 'goal' => 5, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 26, 'parent_id' => 40, 
			'type_id' => 2, 'team_id' => null],
			['id' => 43, 'name' => 'Década', 'description' => 'Cumplir diez años trabajando en la empresa', 
			'awarded_points' => 500, 'redeemable_points' => 500, 'goal' => 10, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 27, 'parent_id' => 41, 
			'type_id' => 2, 'team_id' => null],
			['id' => 44, 'name' => 'Doble década', 'description' => 'Cumplir veinte años trabajando en la empresa', 
			'awarded_points' => 1000, 'redeemable_points' => 1000, 'goal' => 20, 'variable_id' => 6, 'league_id' => null, 'badge_id' => 28, 'parent_id' => 42, 
			'type_id' => 2, 'team_id' => null],
			['id' => 45, 'name' => 'Excelente desempeño', 'description' => 'Completar un curso con calificación del 100%', 'awarded_points' => 50, 
			'redeemable_points' => 50, 'goal' => 1, 'variable_id' => 1, 'league_id' => null, 'badge_id' => 29, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 46, 'name' => 'Buen desempeño', 'description' => 'Completar un curso con calificación superior al 90%', 'awarded_points' => 20, 
			'redeemable_points' => 20, 'goal' => 1, 'variable_id' => 1, 'league_id' => null, 'badge_id' => 30, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 47, 'name' => 'Primer lugar', 'description' => 'Ocupar el primer lugar en la tabla de líderes un mes', 'awarded_points' => 20, 
			'redeemable_points' => 20, 'goal' => 1, 'variable_id' => 6, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 48, 'name' => 'Segundo lugar', 'description' => 'Ocupar el segundo lugar en la tabla de líderes un mes', 'awarded_points' => 12, 
			'redeemable_points' => 12, 'goal' => 2, 'variable_id' => 6, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 49, 'name' => 'Tercer lugar', 'description' => 'Ocupar el tercer lugar en la tabla de líderes un mes', 'awarded_points' => 8, 
			'redeemable_points' => 8, 'goal' => 3, 'variable_id' => 6, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 2, 'team_id' => null],
			['id' => 50, 'name' => 'Abandono de curso', 'description' => 'Abandonar un curso después de iniciado', 'awarded_points' => 20, 
			'redeemable_points' => 20, 'goal' => 1, 'variable_id' => 1, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 5, 'team_id' => null],
			['id' => 51, 'name' => 'Baja calificación', 'description' => 'Obtener una calificación inferior al 50% en un curso', 'awarded_points' => 20, 
			'redeemable_points' => 20, 'goal' => 1, 'variable_id' => 1, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 5, 'team_id' => null],
			['id' => 52, 'name' => 'Tercer intento', 'description' => 'Obtener una calificación inferior al 70% en tres intentos para un curso', 'awarded_points' => 50, 
			'redeemable_points' => 50, 'goal' => 3, 'variable_id' => 1, 'league_id' => null, 'badge_id' => null, 'parent_id' => null, 
			'type_id' => 5, 'team_id' => null]
		];
		\DB::table('missions')->insert($missions);
	}
}